---
fullname: DNAml
shortname: dnaml
namespace: dnaml
organization: CharlesAverill
community: false
action: true
coqdoc: true
dune: true
coqdoc_index: 'docs/latest/coqdoc/toc.html'

synopsis: ML-style genetic programming

description: |-
  An experimental formalization of ML-style genetic programming in Coq

authors:
- name: Charles Averill
  initial: true
  orcid: 0000-0001-6614-1808

maintainers:
- name: Charles Averill
  nickname: CharlesAverill

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.19.1 or later
  opam: '{(>= "8.19.1")}'

tested_coq_opam_versions:
- version: '8.19.1'

keywords:
- name: genetic

documentation: |-
  # Design
  
  I'm taking a lot of cues from [PushGP](http://faculty.hampshire.edu/lspector/push.html)

  Can currently write a list of genes (a series of AST tokens),
  write epigenetic marker functions and "render" a genome
  (a list of genes combined with a list of markers) given
  the appropriate set of mutations (parametrized over genes and markers)
---
